### ISSUE TITLE
Coming soon page Elementor

### ISSUE THREAD

**Issue by CaroleStroud** [themovation/th-widget-pack#166]
I am not able to set a coming soon page without the side bar showing at the bottom of the page despite setting the page without it. I have had to get a plugin to set my site in coming soon mode.
<img width="1270" alt="screen shot 2018-08-15 at 12 09 04" src="https://user-images.githubusercontent.com/42420732/44171341-e37c8e00-a0d1-11e8-8723-7281634c52ad.png">
<img width="1261" alt="screen shot 2018-08-15 at 12 09 15" src="https://user-images.githubusercontent.com/42420732/44171342-e37c8e00-a0d1-11e8-9c8a-c817ba55cb3f.png">

**Comment by CaroleStroud** [comment]
Currently on coming soon mode with another plugin

**Comment by ryanlabelle** [comment]
Hi Carole, can you please create at ticket for us?  

https://themovation.ticksy.com/
