### ISSUE TITLE
Full Width Pages Go to Narrow When Activating Plugin

### ISSUE THREAD

**Issue by scott7414** [themovation/th-widget-pack#180]
Tried using this plugin on elementor site and when I activate the plugin my full width pages convert to boxed.
Any ideas?

**Comment by ryanlabelle** [comment]
Are you using this with one of our themes? 

https://themeforest.net/user/Themovation

**Comment by scott7414** [comment]
Hey Ryan...  Not using with your theme.. Just came across on here and was trying it out... 
Thanks

**Comment by ryanlabelle** [comment]
Cool. It's designed to work with our themes :)

**Comment by scott7414** [comment]
Ah.. Gotya.. Thanks
