### ISSUE TITLE
Plugin breaks with Hello Elementor theme - Bad path

### ISSUE THREAD

**Issue by raelshark** [themovation/th-widget-pack#195]
When switching to the Hello Elementor theme, the plugin breaks because of a failure to open the `class-hfe-default-compat.php` file. This appears to be a bad path specific to the Hello handling here:

https://github.com/themovation/th-widget-pack/blob/6de4be138b79fe7ff3d3febd70ffa6d125e6fa64/header-footer/themes/hello-elementor/class-hfe-hello-elementor-compat.php#L27

It looks like the code is missing the `header-footer/` part of the path.

**Comment by raelshark** [comment]
Let me know if you'd like a PR for this.

**Comment by ryanlabelle** [comment]
Thank you. You should be able to deactivate the plugin because it's not designed to be used with other themes. Only themes developed by Themovation. Does that help? Any reason you need to switch to the Hello theme?
