### ISSUE TITLE
Plugin breaks site

### ISSUE THREAD

**Issue by Bizzire** [themovation/th-widget-pack#209]
When Plugin is active the site breaks with a 'Critical Error' message. Deactivating the plugin fixes the issue. Any help would be greatly appreciated.

**Comment by ryanlabelle** [comment]
Thanks. What theme are you using it with? Can you please create a ticket for us? 

https://themovation.ticksy.com/

**Comment by Bizzire** [comment]
We have a slightly customized version of the Elementor hello theme. Which
isn't in the dropdown on your site.

**Comment by ryanlabelle** [comment]
Interesting. We haven't tested this plugin for compatibility for Hello, however we are releasing a new plugin that provides all that you get in this plugin and it is compatible with Hello and Astra. Would you like to do some beta testing? We should be live with the Beta this week. :)
