### ISSUE TITLE
register_widget_type' and 'widgets_registered Deprecated

### ISSUE THREAD

**Issue by markbosky** [themovation/th-widget-pack#214]
register_widget_type' or 'widgets_registered functions have been deprecated in Elementor v3.1.6

This change breaks th-widget-pack plugin functionality. 

https://github.com/elementor/elementor/issues/23745
https://developers.elementor.com/v3-5-planned-deprecations/

**Comment by rami-elementor** [comment]
How to fix the issue:

https://developers.elementor.com/docs/deprecations/advanced-example/

**Comment by rami-elementor** [comment]
@ryanlabelle I've seen https://github.com/themovation/th-widget-pack/pull/205 PR.

You need to replace the deprecated `_register_controls` methods with `register_controls`:
https://github.com/search?q=repo%3Athemovation%2Fth-widget-pack+_register_controls&type=code

Furthermore, you need to update all the `register_widget_type` instances:
https://github.com/search?q=repo%3Athemovation%2Fth-widget-pack%20register_widget_type&type=code
To register the widgets the correct way.

**Comment by ryanlabelle** [comment]
Hey @rami-elementor and @markbosky , we fixed this and rolled out a new version yesterday. :) We will merge with Master in the next few days. If you have a copy of our themes, you should be notified in the dashboard. 

Thanks for letting us know.
